namespace Sanity
{
    [default_interface]
    runtimeclass SanityEngine
    { 
        /*!
         * \brief Initializes the engine to render with the provided swapchain
         * 
         * Note that this doesn't create a new instance of SanityEngine. As the method_name attribute implies, this
         * method gets the current instance of SanityEngine - or, if there isn't one, this method will make one
         */
        [method_name("GetInstance")] SanityEngine();

        /*!
         * \brief Tells SanityEngine to render to a specific swap chain panel
         * 
         * This method breaks the connection to whatever swapchain panel SanityEngine is currently rendering to. It is
         * the caller's responsibility to manage the swapchains
         */
        void SetRenderSurface(Windows.UI.Xaml.Controls.SwapChainPanel renderSurface);

        /*!
         * \brief Ticks the SanityEngine simulation and rendering by the specified number of seconds
         */
        void Tick(Double deltaTime);
    }
}