#pragma once

#include <unordered_set>

#include <glm/ext/quaternion_float.hpp>
#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>

// The horus::component

struct [[horus::component]] TransformComponent {
    [[horus::field]] glm::vec3 position{0};

    [[horus::field]] glm::quat rotation{};

    [[horus::field]] glm::vec3 scale{1};

    [[nodiscard]] [[horus::method]] __forceinline glm::vec3 get_forward_vector() const;

    [[nodiscard]] [[horus::method]] __forceinline glm::vec3 get_right_vector() const;

    [[nodiscard]] [[horus::method]] __forceinline glm::vec3 get_up_vector() const;

#pragma region Autogenerated

    // Autogenerated identifier for this component type. Allows this component to type to be saved to disk and
    // ReSharper disable once CppInconsistentNaming
    uint64_t _handle{0};
#pragma endregion
};

inline glm::vec3 TransformComponent::get_forward_vector() const {
    constexpr auto global_forward = glm::vec3{0, 0, 1};
    return global_forward * rotation;
}

inline glm::vec3 TransformComponent::get_right_vector() const {
    constexpr auto global_right = glm::vec3{1, 0, 0};
    return global_right * rotation;
}

inline glm::vec3 TransformComponent::get_up_vector() const {
    constexpr auto global_up = glm::vec3{0, 1, 0};
    return global_up * rotation;
}

struct [[component]] TagComponent {
    [[serialize]] std::unordered_set<std::string> tags;
};
